
site_name: Assembly
site_description: ""
site_url: "https://mardix.github.com/assembly"
copyright: 'Copyright &copy; 2019++ Mardix'

repo_url: https://github.com/mardix/assembly
repo_name: "assembly"
theme: "material" # readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs

extra:
  palette:
    primary: 'Brown'
    accent: 'Amber'

pages:

  - Home: index.md
  - Tutorial: setup.md
  - Application:
    - Config: config.md
    - Views: views.md
    - Models: models.md
    - Templates: templates.md
    - Static: static.md
    - CLI: cli.md
    - Deployment: deploy.md
  
  - Utils: utils.md
  - Pagination: pagination.md
  - Signals: signals.md
  - Logging: logging.md
  - Exceptions: exceptions.md
  
  
#  - Snippets:
#    - Home: snippets/index.md


