
site_name: Assembly
site_description: ""
site_url: "https://mardix.github.com/assembly"
copyright: 'Copyright &copy; 2019 - Forever Mardix'

repo_url: https://github.com/mardix/assembly
repo_name: "assembly"

theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'deep purple'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'local_florist'
  feature:
      tabs: false

 
markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs




pages:
  - Overview: index.md
  - Installation: install.md 
  - WSGI.py: wsgipy.md
  - Configuration: config.md  
  - Application:
    - Views: application/views.md
    - Models: application/models.md
    - Templates: application/templates.md
    - Static: application/static.md
    - HTTPError: application/httperror.md
  - Advanced:
    - Signals: advanced/signals.md
    - Date: advanced/date.md
    - Caching: advanced/caching.md    
    - CSFR: advanced/csrf.md
    - Mail: advanced/mail.md
    - Storage: advanced/storage.md
    - Sessions: advanced/sessions.md
    - Pagination: advanced/pagination.md    
    - Utils: advanced/utils.md    
  - CLI: cli.md
  - Deployment: deploy.md
  - Tutorials: tutorials.md   
  


