
site_name: Assembly
site_description: ""
site_url: "https://mardix.github.com/assembly"
copyright: 'Copyright &copy; 2019 - Forever Mardix'

repo_url: https://github.com/mardix/assembly
repo_name: "assembly"
theme: "material" # readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs

extra:
  palette:
    primary: 'Brown'
    accent: 'Amber'

pages:

  - Home: index.md
  - Tutorial: tutorial.md
  - Application:
    - Config: application/config.md
    - Views: application/views.md
    - Models: application/models.md
    - Templates: application/templates.md
    - Static: application/static.md
    - HTTPError: application/httperror.md
    - CLI: application/cli.md
    - Deployment: application/deploy.md
  - Advanced:
    - Utils: advanced/utils.md
    - Pagination: advanced/pagination.md
    - Signals: advanced/signals.md
  
  
#  - Snippets:
#    - Home: snippets/index.md


